# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c985d0e80d71f3a133797648dd608ff912c7ea7a0096719dc5de9a4adb08a94526687ed7804ed18c6b64105565e7fdb46413011b0045ae31e89899073e1a9523

test:
  secret_key_base: 25efe461a837ffb35e19e82c9ba3f12d8ee7c028b6badb3becb1f922e2792843f59e56e33767f9ebba2a9c2680463ff09307f9c4449ae321d70738590c5b4740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
